global:
  scrape_interval:     10s
  evaluation_interval: 10s 

  external_labels:
      monitor: 'ransomware'

scrape_configs:
  - job_name: 'ransomexporter'
    scrape_interval: 10s
    static_configs:
         - targets: ['zertoexporter:9999']