{
 "title": "Datastore Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "SiteName", "label": "Site Name", "query": { "query": "query_result(vm_actualrpo{})" } }
  ]
 },
 "panels": [
  {
   "title": "Datastore Recovery Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "datastore_usage_zerto_recovery_usedinbytes{SiteName=\"$SiteName\"}",
     "legendFormat": "{{DatastoreName}}"
    }
   ]
  },
  {
   "title": "Datastore Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "datastore_usage_usedinbytes{SiteName=\"$SiteName\"}",
     "legendFormat": "{{DatastoreName}}"
    }
   ]
  },
  {
   "title": "Journal Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "datastore_usage_zerto_journal_usedinbytes{SiteName=\"$SiteName\"}",
     "legendFormat": "{{DatastoreName}}"
    }
   ]
  },
  {
   "title": "Scratch Journal Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "datastore_usage_zerto_scratch_usedinbytes{SiteName=\"$SiteName\"}",
     "legendFormat": "{{DatastoreName}}"
    }
   ]
  },
  {
   "title": "Incoming VMs per Datastore",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "datastore_incoming_vms{SiteName=\"$SiteName\"}",
     "legendFormat": "{{DatastoreName}}"
    }
   ]
  },
  {
   "title": "Outgoing VMs per Datastore",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "datastore_outgoing_vms{SiteName=\"$SiteName\"}",
     "legendFormat": "{{DatastoreName}}"
    }
   ]
  },
  {
   "title": "Zerto VRA Usage per Datastore",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "datastore_usage_zerto_appliances_usedinbytes{SiteName=\"$SiteName\"}",
     "legendFormat": "{{DatastoreName}}-Used"
    },
    {
     "expr": "datastore_usage_zerto_appliances_provisionedinbytes",
     "legendFormat": "{{DatastoreName}}-Provisioned"
    }
   ]
  }
 ]
}