{
 "title": "Zerto Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "SiteName", "label": "Site Name", "query": { "query": "query_result(vm_actualrpo{})" } }
  ]
 },
 "panels": [
  {
   "title": "Average RPO",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vm_actualrpo{SiteName=\"$SiteName\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Protected VMs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vpg_vms_count{SiteName=\"$SiteName\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPG RPO History Map",
   "type": "heatmap",
   "gridPos": { "h": 25, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "vpg_actual_rpo{SiteName=\"$SiteName\"}",
     "legendFormat": "{{VpgName}}"
    }
   ]
  },
  {
   "title": "RPO - Per VM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vm_actualrpo{SiteName=\"$SiteName\"}",
     "legendFormat": "{{VmName}}"
    }
   ]
  },
  {
   "title": "VPG Journal History Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "vpg_actual_history_in_minutes{SiteName=\"$SiteName\"}",
     "legendFormat": "{{VpgName}} - Actual"
    },
    {
     "expr": "vpg_configured_history_in_minutes",
     "legendFormat": "{{VpgName}} - Configured Limit"
    }
   ]
  },
  {
   "title": "Write Throughput (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "vm_throughput_in_mb{SiteName=\"$SiteName\"}",
     "legendFormat": "{{VmName}}"
    }
   ]
  },
  {
   "title": "Journal Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "vm_journal_used_storage_mb{SiteName=\"$SiteName\"}",
     "legendFormat": "{{VmName}}"
    }
   ]
  },
  {
   "title": "IOps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "vm_iops{SiteName=\"$SiteName\"}",
     "legendFormat": "{{VmName}}"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "vm_NetworkTrafficCounterInMBs{SiteName=\"$SiteName\"}",
     "legendFormat": "{{VmName}}"
    }
   ]
  }
 ]
}